### ISSUE TITLE
Roadmap to 3.0.0

### ISSUE THREAD

**Issue by Codeusa** [Codeusa/aurous-app#14]
For Aurous 3.0.0 I plan to implement a bundle of new features/better existing ones to make development easier. 

### This is including but not limited to the following:

- [x] Rebuilding the way fetchers/playlist compilers work
- [ ] A better way of managing ui components
- [x] Expanding player functionality to move away from static based playback. 
- [x] Expanding the Javascript engine for content processing

### To reach version 3.0.0 this following features must be implemented:

- [ ] Stream downloading/conversions 
- [x]  A share ability which provides a easy way for sharing playlist with other users
- [ ]  A GUI which allows for easy editing of playlist: i.e users can set their own album art. for songs.
- [x] Twitter OAUTH integration 
- [ ] Soundcloud import support
- [x] Plug.DJ Playlist grabber

### A few bugs have been noted, the following need to be fixed

- [x] App freezes if an error is encountered that is related to playback
- [x] Gaps when importing VK songs in the playlist, unable to delete since its white space.
- [x] Errors on importing leave a nulled playlist which can crash the app is attempted to open. 
- [x] Alertify4J custom build has a Debug message in it that I meant to remove. 

If you want to suggest any features, expansions or bug fixes feel free to leave them here.
